apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omnixys-person.fullname" . }}-config
  namespace: {{ include "omnixys-person.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "omnixys-person.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: omnixys
data:
  application.yaml: |
    server:
      port: {{ .Values.env.SERVER_PORT | default 7001 }}
    spring:
      profiles:
        active: {{ tpl .Values.env.ACTIVE_PROFILE . | quote }}
      data:
        mongodb:
          uri: {{ tpl .Values.secrets.MONGODB_URI . | quote }}
          database: {{ tpl .Values.env.MONGODB_DATABASE . | quote }}
