apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omnixys-person.fullname" . }}-secret
  namespace: {{ include "omnixys-person.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "omnixys-person.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: omnixys
type: Opaque
data:
  MONGODB_URI: {{ .Values.secrets.MONGODB_URI | b64enc }}
  MONGODB_USER_NAME: {{ .Values.secrets.MONGODB_USER_NAME | b64enc }}
  MONGODB_USER_PASSWORT: {{ .Values.secrets.MONGODB_USER_PASSWORT | b64enc }}

  KC_SERVICE_SECRET: {{ .Values.secrets.KC_SERVICE_SECRET | b64enc }}
  KC_SERVICE_CLIENT_ID: {{ .Values.secrets.KC_SERVICE_CLIENT_ID | b64enc }}
  KC_SERVICE_REALM: {{ .Values.secrets.KC_SERVICE_REALM | b64enc }}
  KC_SERVICE_HOST: {{ .Values.secrets.KC_SERVICE_HOST | b64enc }}
  KC_SERVICE_PORT: {{ .Values.secrets.KC_SERVICE_PORT | b64enc }}

  KAFKA_HOST: {{ .Values.secrets.KAFKA_HOST | b64enc }}
  TEMPO_HOST: {{ .Values.secrets.TEMPO_HOST | b64enc }}
  
  NVD_API_KEY: {{ .Values.secrets.NVD_API_KEY | b64enc }}
  SNYK_TOKEN: {{ .Values.secrets.SNYK_TOKEN | b64enc }}
  SONAR_TOKEN: {{ .Values.secrets.SONAR_TOKEN | b64enc }}
  CODECOV_TOKEN: {{ .Values.secrets.CODECOV_TOKEN | b64enc }}
