apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omnixys-person.fullname" . }}-tls
  namespace: {{ include "omnixys-person.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "omnixys-person.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: tls
    app.kubernetes.io/part-of: omnixys
type: kubernetes.io/tls
data:
  tls.key: {{ .Values.tls.key | b64enc }}
  tls.crt: {{ .Values.tls.crt | b64enc }}
