# .github/workflows/deploy.yml

name: Deploy Omnixys Service via Helm

on:
  workflow_dispatch:

env:
  HELM_RELEASE: ${{ secrets.HELM_RELEASE }}        # z. B. omnixys-profile
  HELM_CHART_PATH: ./charts/${{ secrets.SERVICE }} # Pfad zu deinem Helm-Chart
  HELM_NAMESPACE: omnixys                           # Namespace für alle Services
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_NAME: ${{ secrets.DOCKER_USER }}/${{ secrets.SERVICE }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Set up Docker auth for image pull
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Helm Upgrade
        run: |
          helm upgrade --install $HELM_RELEASE $HELM_CHART_PATH \
            --namespace $HELM_NAMESPACE --create-namespace \
            --set image.repository=$IMAGE_NAME \
            --set image.tag=$IMAGE_TAG
